name: dart_serde
description: Serialize and Deserialize Json into and from classes, aim to give a nice and friendly interface, inspired by the Serde package from rust
version: 1.0.2
author: Eduardo Sabino da Silva Aikin <eduardoaikin@gmail.com>
homepage: https://github.com/EdSabino/dart_serde

environment:
  sdk: ">=2.1.0 <3.0.0"
