  
targets:
  $default:
    builders:
      serde_generator|serde:
        enabled: true

builders:
  serde:
    target: ":serde_generator"
    import: "package:serde_generator/builder.dart"
    builder_factories: ["generateJsonSerializer"]
    build_extensions: {".dart": [".serde_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]