name: serde_generator
description: A new Flutter package.
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  serde:
    path: ../serde/
  
dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
