name: serde_generator
description: The generator for the dart_serde package, is responsible for generate the code that will serialize or deserialize an class
version: 1.0.9
author: Eduardo Sabino da SIlva Aikin <eduardoaikin@gmail.com>
homepage: https://github.com/EdSabino/dart_serde

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.38.2
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  serde: ^1.0.6
  
dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.0.0
  test: ^1.0.0
