name: serde
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  serde_generator:
    path: ../serde_generator/

dev_dependencies:
  test: ^1.0.0